---
- name: update all
  hosts: all
  become: yes
  
  tasks:
  - name: Ensure httpd installed
    package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Ensure httpd started
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: Ensure httpd enabled
    service:
      name: httpd
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Ensure apt updated
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"    

  - name: Ensure Apache installed
    apt:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu" 

  - name: Ensure Apache started
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu" 

  - name: Ensure Apache enabled
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu" 

...

