---
- name: update all
  hosts: all
  become: yes
  vars:
   http_port: 9090
  
  tasks:
  - name: Ensure config file updated
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf

  - name: Ensure SELINUX permissive
    selinux:
      policy: targeted
      state: permissive

  - name: Ensure httpd restarted
    service:
      name: httpd
      state: restarted
...

