---
- name: update all
  hosts: all
  become: yes
  vars:
   http_port: 9090
  handlers:
  - name: Restart http
    service:
      name: httpd
      state: restarted
 
  tasks:
  - name: Ensure config file updated
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - Restart http

  - name: Ensure SELINUX permissive
    selinux:
      policy: targeted
      state: permissive
  
  - name: Ensure static file updated
    copy:
      src: date.php
      dest: /var/www/html/date.php

  - name: Ensure PHP installed
    package:
      name: php
      state: present
    notify:
    - Restart http

...

